# Generated by Django 3.1.7 on 2021-06-10 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20210610_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_bill',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 10, 18, 40, 14, 955596)),
        ),
    ]
