# Generated by Django 3.1.7 on 2021-06-15 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20210615_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='starting_date',
        ),
        migrations.AlterField(
            model_name='membership',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 15, 54, 37, 62419)),
        ),
    ]
