# Generated by Django 3.1.7 on 2021-06-15 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_auto_20210615_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='membership',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 15, 55, 19, 92117)),
        ),
    ]
