# Generated by Django 3.1.7 on 2021-06-15 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20210615_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 17, 18, 17, 928016)),
        ),
    ]
