# Generated by Django 3.1.7 on 2021-06-15 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_auto_20210615_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silver_3m', models.IntegerField(default=0)),
                ('silver_6m', models.IntegerField(default=0)),
                ('gold_3m', models.IntegerField(default=0)),
                ('gold_6m', models.IntegerField(default=0)),
                ('platinum_3m', models.IntegerField(default=0)),
                ('platinum_6m', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='membership',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 17, 48, 39, 211975)),
        ),
    ]
