# Generated by Django 3.1.7 on 2021-06-15 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_auto_20210615_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 0, 0, 39, 167385)),
        ),
    ]
