# Generated by Django 3.1.7 on 2021-06-16 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0071_auto_20210616_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 11, 58, 41, 675089)),
        ),
    ]
